import { CurrencyPipe } from '@angular/common';
import { Component, inject, signal, OnInit, ElementRef } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { firstValueFrom } from 'rxjs';
import { CartService } from '../../../core/orders/cart.service';
import { CheckoutPreview, CheckoutRequest, CustomerOrder, OrderService } from '../../../core/orders/order.service';
interface Attempt { checkoutKey:string; approvalUrl:string|null; state:string; environment:string; checkout:CheckoutRequest; preview:CheckoutPreview; address:Address; order:CustomerOrder|null; }
interface Address { addressLine1:string; addressLine2:string; city:string; state:string; postalCode:string; countryCode:string; }
@Component({selector:'app-demo-checkout',standalone:true,imports:[CurrencyPipe,RouterLink,ReactiveFormsModule],templateUrl:'./demo-checkout.component.html',styleUrl:'./demo-checkout.component.scss'})
export class DemoCheckoutComponent implements OnInit {
 private readonly host:ElementRef<HTMLElement>=inject(ElementRef);
 private readonly http=inject(HttpClient);private readonly orders=inject(OrderService);private readonly cart=inject(CartService);private readonly route=inject(ActivatedRoute);
 protected readonly config=signal({enabled:false,environment:'sandbox'});protected readonly preview=signal<CheckoutPreview|null>(null);protected readonly order=signal<CustomerOrder|null>(null);protected readonly pending=signal<Attempt|null>(null);protected readonly busy=signal(true);protected readonly error=signal('');protected readonly notice=signal('');
 protected readonly form=inject(FormBuilder).nonNullable.group({addressLine1:['',[Validators.required,Validators.minLength(3),Validators.pattern(/\S/),Validators.maxLength(150)]],addressLine2:['',Validators.maxLength(150)],city:['',[Validators.required,Validators.pattern(/\S/),Validators.maxLength(80)]],state:['',Validators.maxLength(80)],postalCode:['',Validators.maxLength(30)],countryCode:['US',Validators.required]});
 protected readonly countries='AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX AZ BA BB BD BE BF BG BH BI BJ BL BM BN BO BQ BR BS BT BV BW BY BZ CA CC CD CF CG CH CI CK CL CM CN CO CR CU CV CW CX CY CZ DE DJ DK DM DO DZ EC EE EG EH ER ES ET FI FJ FK FM FO FR GA GB GD GE GF GG GH GI GL GM GN GP GQ GR GS GT GU GW GY HK HM HN HR HT HU ID IE IL IM IN IO IQ IR IS IT JE JM JO JP KE KG KH KI KM KN KP KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MF MG MH MK ML MM MN MO MP MQ MR MS MT MU MV MW MX MY MZ NA NC NE NF NG NI NL NO NP NR NU NZ OM PA PE PF PG PH PK PL PM PN PR PS PT PW PY QA RE RO RS RU RW SA SB SC SD SE SG SH SI SJ SK SL SM SN SO SR SS ST SV SX SY SZ TC TD TF TG TH TJ TK TL TM TN TO TR TT TV TW TZ UA UG UM US UY UZ VA VC VE VG VI VN VU WF WS YE YT ZA ZM ZW'.split(' ').map(code=>({code,name:new Intl.DisplayNames(['en'],{type:'region'}).of(code)||code})).sort((a,b)=>a.name.localeCompare(b.name));
 private checkout:CheckoutRequest={lines:[],customRequestId:null};private key:string|null=null;
 async ngOnInit(){try{this.config.set(await firstValueFrom(this.http.get<{enabled:boolean;environment:string}>('/api/paypal/config')));const q=this.route.snapshot.queryParamMap;const key=q.get('attempt');const a=await firstValueFrom(this.http.get<Attempt|null>(key?'/api/paypal/attempts/'+encodeURIComponent(key):'/api/paypal/pending'));if(a){this.apply(a);if(q.has('paypalReturn'))await this.action('capture');else if(q.has('paypalCancel'))await this.action('cancel');}if(!this.pending()&&!this.order())await this.review();}catch(e){this.fail(e);}finally{this.busy.set(false);}}
 private async review(){this.checkout={lines:this.route.snapshot.queryParamMap.has('quote')?[]:this.cart.lines(),customRequestId:this.route.snapshot.queryParamMap.get('quote')};this.preview.set(null);if(this.checkout.lines.length||this.checkout.customRequestId)this.preview.set(await firstValueFrom(this.orders.preview(this.checkout)));}
 private apply(a:Attempt){this.checkout=a.checkout;this.key=a.checkoutKey;this.preview.set(a.preview);this.form.patchValue(a.address);if(a.order){this.order.set(a.order);this.pending.set(null);this.cart.removePurchased(a.checkout.lines);this.notice.set('Your payment is confirmed. Thank you for your order.');}else if(a.state==='Abandoned'){this.pending.set(null);this.key=null;this.form.enable();this.notice.set('Checkout cancelled. Your bag has been kept.');}else{this.pending.set(a);this.form.disable();this.notice.set(a.state==='Pending'?'PayPal is processing your payment. Check its status before starting another checkout.':'Your checkout is saved. Continue with PayPal or check your payment status.');}}
 protected async pay(){if(this.busy()||!this.config().enabled||!this.preview())return;this.form.markAllAsTouched();if(this.form.invalid){this.host.nativeElement.querySelector<HTMLElement>('input.ng-invalid, select.ng-invalid')?.focus();return;}this.busy.set(true);this.error.set('');try{this.key??=crypto.randomUUID();const a=await firstValueFrom(this.http.post<Attempt>('/api/paypal/orders',{checkoutKey:this.key,checkout:this.checkout,expectedTotal:this.preview()!.total,address:this.form.getRawValue()}));this.apply(a);this.redirect(a);}catch(e){this.fail(e);await this.recover();}finally{this.busy.set(false);}}
 protected async action(action:'capture'|'resume'|'cancel'){const key=this.pending()?.checkoutKey;if(!key)return;this.busy.set(true);this.error.set('');try{const a=await firstValueFrom(this.http.post<Attempt>('/api/paypal/attempts/'+key+'/'+action,{}));this.apply(a);if(action==='resume')this.redirect(a);if(a.state==='Abandoned')await this.review();}catch(e){this.fail(e);}finally{this.busy.set(false);}}
 protected invalid(field:keyof Address):boolean {const control=this.form.controls[field];return control.enabled&&control.touched&&control.invalid;}
 protected fieldError(field:keyof Address):string {
  const control=this.form.controls[field];const labels:Record<keyof Address,string>={addressLine1:'street address',addressLine2:'apartment or suite',city:'city',state:'state or province',postalCode:'ZIP or postal code',countryCode:'country'};
  if(control.hasError('required')||control.hasError('pattern'))return 'Please enter your '+labels[field]+'.';
  if(control.hasError('minlength'))return 'Enter at least '+control.errors!['minlength'].requiredLength+' characters.';
  if(control.hasError('maxlength'))return 'Use no more than '+control.errors!['maxlength'].requiredLength+' characters.';
  return 'Please check your '+labels[field]+'.';
 }
 private redirect(a:Attempt){if(a.order||!a.approvalUrl||a.state==='Pending')return;const u=new URL(a.approvalUrl);if(u.protocol==='https:'&&(u.hostname==='paypal.com'||u.hostname.endsWith('.paypal.com')))window.location.assign(u.href);}
 private async recover(){try{const a=await firstValueFrom(this.http.get<Attempt|null>('/api/paypal/pending'));if(a)this.apply(a);else {this.key=null;await this.review();}}catch{}}
 private fail(e:unknown){this.error.set((e as {error?:{error?:string}})?.error?.error||'Unable to confirm your payment right now. Your checkout reference is kept; please try again.');}
}
