import { isPendantCategory } from '../../../core/catalog/category-names';
import { DialogFocusDirective } from '../../../shared/ui/dialog-focus.directive';
import { HttpErrorResponse } from '@angular/common/http';
import { ChangeDetectionStrategy, Component, OnDestroy, OnInit, computed, inject, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { forkJoin, finalize } from 'rxjs';
import { Category, Product, ProductOption, ProductOptionType } from '../../../core/catalog/catalog.models';
import { StorefrontCatalogService } from '../../../core/catalog/storefront-catalog.service';
import { CustomRequestService } from '../../../core/custom-requests/custom-request.service';
import { KsButtonDirective, ProductCardComponent } from '../../../shared/ui';

@Component({ selector: 'app-custom-jewelry', standalone: true, imports: [DialogFocusDirective, ReactiveFormsModule, RouterLink, KsButtonDirective, ProductCardComponent], templateUrl: './custom-jewelry.component.html', styleUrls: ['./custom-form.component.scss', './custom-jewelry.component.scss', './custom-hero.component.scss'], changeDetection: ChangeDetectionStrategy.OnPush })
export class CustomJewelryComponent implements OnInit, OnDestroy {
  private readonly catalog = inject(StorefrontCatalogService); private readonly requests = inject(CustomRequestService); private readonly router = inject(Router); private readonly previews = new Map<File, string>();
  protected readonly loadError = signal(false);
  protected readonly categories = signal<Category[]>([]); protected readonly options = signal<ProductOption[]>([]); protected readonly customProducts = signal<Product[]>([]); protected readonly formOpen = signal(false); protected readonly selectedCategoryId = signal(''); protected readonly selectedOptionIds = signal<string[]>([]); protected readonly files = signal<File[]>([]); protected readonly loading = signal(true); protected readonly saving = signal(false); protected readonly error = signal('');
  protected readonly optionGroups = computed(() => { const allowed = new Set(this.allowedTypes(this.selectedCategory()?.name ?? '')); return [...new Set(this.options().filter(option => option.isActive && allowed.has(option.type)).map(option => option.type))].sort((a,b) => (a === 'CustomPendantStyle' ? -1 : b === 'CustomPendantStyle' ? 1 : 0)).map(type => ({ type, label: this.label(type), options: this.options().filter(option => option.isActive && option.type === type) })); });
  protected readonly selectedStyle = computed(() => this.options().find(option => option.type === 'CustomPendantStyle' && this.optionSelected(option.id)));
  protected readonly selectedCategory = computed(() => this.categories().find(category => category.id === this.selectedCategoryId()));
  protected readonly form = new FormGroup({ customerName: new FormControl('', { nonNullable: true, validators: [Validators.required, Validators.maxLength(150)] }), email: new FormControl('', { nonNullable: true, validators: [Validators.required, Validators.email] }), phone: new FormControl('', { nonNullable: true, validators: [Validators.required, Validators.minLength(7), Validators.maxLength(32)] }), description: new FormControl('', { nonNullable: true, validators: [Validators.required, Validators.maxLength(4000)] }) });
  ngOnInit(): void { this.loading.set(true); this.loadError.set(false); forkJoin({ categories: this.catalog.getCustomCategories(), options: this.catalog.getOptions(), products: this.catalog.getCustomProducts() }).subscribe({ next: value => { this.categories.set(value.categories.filter(category => !category.parentId)); this.options.set(value.options); this.customProducts.set(value.products); this.loading.set(false); }, error: () => { this.loadError.set(true); this.error.set('The Custom Jewellery page could not be loaded.'); this.loading.set(false); } }); }
  ngOnDestroy(): void { this.files().forEach(file => this.revoke(file)); }
  protected chooseCategory(id: string): void { this.selectedCategoryId.set(id); this.selectedOptionIds.set([]); }
  protected selectOption(type: ProductOptionType, id: string): void { const sameTypeIds = new Set(this.options().filter(option => option.type === type).map(option => option.id)); this.selectedOptionIds.update(values => [...values.filter(value => !sameTypeIds.has(value)), id]); }
  protected optionSelected(id: string): boolean { return this.selectedOptionIds().includes(id); }
  protected openForm(): void { this.formOpen.set(true); this.error.set(''); }
  protected closeForm(): void { if (this.saving()) return; this.formOpen.set(false); this.error.set(''); }
  protected addFiles(event: Event): void { const input = event.target as HTMLInputElement; const chosen = Array.from(input.files ?? []); input.value = ''; if (chosen.some(file => !['image/jpeg','image/png','image/webp'].includes(file.type) || file.size > 10 * 1024 * 1024)) { this.error.set('Choose JPEG, PNG or WebP images up to 10 MB each.'); return; } const existing = this.files(); const keys = new Set(existing.map(file => this.fileKey(file))); const added = chosen.filter(file => !keys.has(this.fileKey(file))); if (existing.length + added.length > 6) { this.error.set('You can upload a maximum of 6 reference images.'); return; } added.forEach(file => this.previews.set(file, URL.createObjectURL(file))); this.files.set([...existing, ...added]); this.error.set(''); }
  protected preview(file: File): string { return this.previews.get(file) ?? ''; }
  protected removeFile(index: number): void { const file = this.files()[index]; if (file) this.revoke(file); this.files.update(files => files.filter((_, current) => current !== index)); }
  protected submit(): void { if (!this.selectedCategoryId()) { this.error.set('Select the jewellery category.'); return; } if (this.form.invalid) { this.form.markAllAsTouched(); this.error.set('Complete all required contact and design fields.'); return; } if (this.files().length < 1) { this.error.set('Upload at least one reference image.'); return; } const value = this.form.getRawValue(); const body = new FormData(); body.append('categoryId', this.selectedCategoryId()); this.selectedOptionIds().forEach(id => body.append('optionIds', id)); body.append('customerName', value.customerName); body.append('email', value.email); body.append('phone', value.phone); body.append('description', value.description); this.files().forEach(file => body.append('files', file)); this.saving.set(true); this.error.set(''); this.requests.create(body).pipe(finalize(() => this.saving.set(false))).subscribe({ next: result => { this.requests.remember(result); this.router.navigate(['/custom/requests'], { queryParams: { created: result.request.requestNumber } }); }, error: error => this.error.set(error instanceof HttpErrorResponse ? error.error?.error ?? 'The request could not be submitted.' : 'The request could not be submitted.') }); }
  private allowedTypes(category: string): ProductOptionType[] { const name = category.toLowerCase(); if (name.includes('grill')) return ['Color']; if (name.includes('brace')) return ['BraceletStoneSize','BraceletSize','Color']; if (name.includes('ring')) return ['RingSize','Color']; if (isPendantCategory(name.replaceAll('+',' '))) return name.includes('chain') || name.includes('set') ? ['CustomPendantStyle','PendantSize','Color','ChainSize','ChainWidth','ChainDiamondSize'] : ['CustomPendantStyle','PendantSize','Color']; if (name.includes('chain')) return ['ChainSize','ChainWidth','ChainDiamondSize','Color']; return []; }
  private label(type: string): string { return ({ CustomPendantStyle:'Pendant style',BraceletStoneSize:'Stone size',BraceletSize:'Bracelet size',RingSize:'Ring size',PendantSize:'Pendant size',ChainSize:'Chain size',ChainWidth:'Chain width',ChainDiamondSize:'Diamond size',Color:'Color' } as Record<string,string>)[type] ?? type; }
  private fileKey(file: File): string { return `${file.name}:${file.size}:${file.lastModified}`; } private revoke(file: File): void { const url = this.previews.get(file); if (url) URL.revokeObjectURL(url); this.previews.delete(file); }
}
