// <auto-generated />
using System;
using KsSquare.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KsSquare.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260912063300_OrderCourierTracking")]
    partial class OrderCourierTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CustomJewelryRequestProductOption", b =>
                {
                    b.Property<Guid>("CustomJewelryRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("custom_jewelry_request_id");

                    b.Property<Guid>("OptionsId")
                        .HasColumnType("uuid")
                        .HasColumnName("options_id");

                    b.HasKey("CustomJewelryRequestId", "OptionsId")
                        .HasName("pk_custom_jewelry_request_options");

                    b.HasIndex("OptionsId")
                        .HasDatabaseName("ix_custom_jewelry_request_options_options_id");

                    b.ToTable("custom_jewelry_request_options", (string)null);
                });

            modelBuilder.Entity("KsSquare.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_verified");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_users_role");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("KsSquare.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<long?>("ImageContentLength")
                        .HasColumnType("bigint")
                        .HasColumnName("image_content_length");

                    b.Property<string>("ImageContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("image_content_type");

                    b.Property<string>("ImageObjectKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("image_object_key");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<bool>("ShowInCustom")
                        .HasColumnType("boolean")
                        .HasColumnName("show_in_custom");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_slug")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("ParentId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_parent_id_name")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("KsSquare.Domain.Entities.CustomJewelryRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessTokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("access_token_hash");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("customer_name");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<decimal?>("FixedPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("fixed_price");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("request_number");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_custom_jewelry_requests");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_custom_jewelry_requests_category_id");

                    b.HasIndex("RequestNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_custom_jewelry_requests_request_number");

                    b.ToTable("custom_jewelry_requests", (string)null);
                });

            modelBuilder.Entity("KsSquare.Domain.Entities.CustomJewelryRequestMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ContentLength")
                        .HasColumnType("bigint")
                        .HasColumnName("content_length");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CustomJewelryRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("custom_jewelry_request_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("object_key");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_custom_jewelry_request_media");

                    b.HasIndex("CustomJewelryRequestId")
                        .HasDatabaseName("ix_custom_jewelry_request_media_custom_jewelry_request_id");

                    b.HasIndex("ObjectKey")
                        .IsUnique()
                        .HasDatabaseName("ix_custom_jewelry_request_media_object_key");

                    b.ToTable("custom_jewelry_request_media", (string)null);
                });

            modelBuilder.Entity("KsSquare.Domain.Entities.CustomerOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CheckoutKey")
                        .HasColumnType("uuid")
                        .HasColumnName("checkout_key");

                    b.Property<string>("Courier")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("courier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid?>("CustomRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("custom_request_id");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("customer_email");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("customer_phone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)")
                        .HasColumnName("delivery_address");

                    b.Property<bool>("IsDemo")
                        .HasColumnType("boolean")
                        .HasColumnName("is_demo");

                    b.Property<string>("ItemsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("items_json");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("order_number");

                    b.Property<string>("PaymentReference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payment_reference");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("payment_status");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_hash");

                    b.Property<string>("ReturnsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("returns_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("tracking_number");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_customer_orders");

                    b.HasIndex("CustomRequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_customer_orders_custom_request_id");

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_customer_orders_order_number");

                    b.HasIndex("CustomerId", "CheckoutKey")
                        .IsUnique()
                        .HasDatabaseName("ix_customer_orders_customer_id_checkout_key");

                    b.HasIndex("CustomerId", "CreatedAt")
                        .HasDatabaseName("ix_customer_orders_customer_id_created_at");

                    b.ToTable("customer_orders", (string)null);
                });

            modelBuilder.Entity("KsSquare.Domain.Entities.EmailOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_attempts");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("purpose");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_email_otps");

                    b.HasIndex("UserId", "Purpose", "CreatedAt")
                        .HasDatabaseName("ix_email_otps_user_id_purpose_created_at");

                    b.ToTable("email_otps", (string)null);
                });

            modelBuilder.Entity("KsSquare.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<decimal>("DiscountPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("discount_percentage");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<bool>("IsFinalSale")
                        .HasColumnType("boolean")
                        .HasColumnName("is_final_sale");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<decimal>("NameFixedPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("name_fixed_price");

                    b.Property<decimal>("NamePricePerLetter")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("name_price_per_letter");

                    b.Property<decimal>("OriginalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("original_price");

                    b.Property<bool>("ShowInCustom")
                        .HasColumnType("boolean")
                        .HasColumnName("show_in_custom");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sku");

                    b.Property<bool>("SupportsNamePersonalization")
                        .HasColumnType("boolean")
                        .HasColumnName("supports_name_personalization");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("ix_products_sku")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("CategoryId", "IsActive", "IsAvailable")
                        .HasDatabaseName("ix_products_category_id_is_active_is_available");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("KsSquare.Domain.Entities.ProductBraceletVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BraceletSizeOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("bracelet_size_option_id");

                    b.Property<Guid?>("BraceletStoneSizeOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("bracelet_stone_size_option_id");

                    b.Property<string>("CombinationKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("combination_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<decimal>("OriginalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("original_price");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_product_bracelet_variants");

                    b.HasIndex("BraceletSizeOptionId")
                        .HasDatabaseName("ix_product_bracelet_variants_bracelet_size_option_id");

                    b.HasIndex("BraceletStoneSizeOptionId")
                        .HasDatabaseName("ix_product_bracelet_variants_bracelet_stone_size_option_id");

                    b.HasIndex("ProductId", "CombinationKey")
                        .IsUnique()
                        .HasDatabaseName("ix_product_bracelet_variants_product_id_combination_key");

                    b.ToTable("product_bracelet_variants", (string)null);
                });

            modelBuilder.Entity("KsSquare.Domain.Entities.ProductChainVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ChainDiamondSizeOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("chain_diamond_size_option_id");

                    b.Property<Guid>("ChainSizeOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("chain_size_option_id");

                    b.Property<Guid?>("ChainWidthOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("chain_width_option_id");

                    b.Property<string>("CombinationKey")
                        .IsRequired()
                        .HasMaxLength(110)
                        .HasColumnType("character varying(110)")
                        .HasColumnName("combination_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<decimal>("OriginalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("original_price");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_product_chain_variants");

                    b.HasIndex("ChainDiamondSizeOptionId")
                        .HasDatabaseName("ix_product_chain_variants_chain_diamond_size_option_id");

                    b.HasIndex("ChainSizeOptionId")
                        .HasDatabaseName("ix_product_chain_variants_chain_size_option_id");

                    b.HasIndex("ChainWidthOptionId")
                        .HasDatabaseName("ix_product_chain_variants_chain_width_option_id");

                    b.HasIndex("ProductId", "CombinationKey")
                        .IsUnique()
                        .HasDatabaseName("ix_product_chain_variants_product_id_combination_key");

                    b.ToTable("product_chain_variants", (string)null);
                });

            modelBuilder.Entity("KsSquare.Domain.Entities.ProductMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("alt_text");

                    b.Property<long>("ContentLength")
                        .HasColumnType("bigint")
                        .HasColumnName("content_length");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("object_key");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_product_media");

                    b.HasIndex("ObjectKey")
                        .IsUnique()
                        .HasDatabaseName("ix_product_media_object_key")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("ProductId", "DisplayOrder")
                        .HasDatabaseName("ix_product_media_product_id_display_order");

                    b.ToTable("product_media", (string)null);
                });

            modelBuilder.Entity("KsSquare.Domain.Entities.ProductOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<long?>("ImageContentLength")
                        .HasColumnType("bigint")
                        .HasColumnName("image_content_length");

                    b.Property<string>("ImageContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("image_content_type");

                    b.Property<string>("ImageObjectKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("image_object_key");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_product_options");

                    b.HasIndex("Type", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_product_options_type_name")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("Type", "IsActive", "DisplayOrder")
                        .HasDatabaseName("ix_product_options_type_is_active_display_order");

                    b.ToTable("product_options", (string)null);
                });

            modelBuilder.Entity("KsSquare.Domain.Entities.ProductPendantVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<decimal>("OriginalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("original_price");

                    b.Property<Guid>("PendantSizeOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("pendant_size_option_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_product_pendant_variants");

                    b.HasIndex("PendantSizeOptionId")
                        .HasDatabaseName("ix_product_pendant_variants_pendant_size_option_id");

                    b.HasIndex("ProductId", "PendantSizeOptionId")
                        .IsUnique()
                        .HasDatabaseName("ix_product_pendant_variants_product_id_pendant_size_option_id");

                    b.ToTable("product_pendant_variants", (string)null);
                });

            modelBuilder.Entity("ProductOptionAssignment", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("ProductOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_option_id");

                    b.HasKey("ProductId", "ProductOptionId")
                        .HasName("pk_product_option_assignments");

                    b.HasIndex("ProductOptionId")
                        .HasDatabaseName("ix_product_option_assignments_product_option_id");

                    b.ToTable("product_option_assignments", (string)null);
                });

            modelBuilder.Entity("ProductSubcategoryAssignment", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("SubcategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("subcategory_id");

                    b.HasKey("ProductId", "SubcategoryId")
                        .HasName("pk_product_subcategory_assignments");

                    b.HasIndex("SubcategoryId")
                        .HasDatabaseName("ix_product_subcategory_assignments_subcategory_id");

                    b.ToTable("product_subcategory_assignments", (string)null);
                });

            modelBuilder.Entity("CustomJewelryRequestProductOption", b =>
                {
                    b.HasOne("KsSquare.Domain.Entities.CustomJewelryRequest", null)
                        .WithMany()
                        .HasForeignKey("CustomJewelryRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_custom_jewelry_request_options_custom_jewelry_requests_cust");

                    b.HasOne("KsSquare.Domain.Entities.ProductOption", null)
                        .WithMany()
                        .HasForeignKey("OptionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_custom_jewelry_request_options_product_options_options_id");
                });

            modelBuilder.Entity("KsSquare.Domain.Entities.Category", b =>
                {
                    b.HasOne("KsSquare.Domain.Entities.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categories_categories_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("KsSquare.Domain.Entities.CustomJewelryRequest", b =>
                {
                    b.HasOne("KsSquare.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_custom_jewelry_requests_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("KsSquare.Domain.Entities.CustomJewelryRequestMedia", b =>
                {
                    b.HasOne("KsSquare.Domain.Entities.CustomJewelryRequest", "Request")
                        .WithMany("Media")
                        .HasForeignKey("CustomJewelryRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_custom_jewelry_request_media_custom_jewelry_requests_custom");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("KsSquare.Domain.Entities.CustomerOrder", b =>
                {
                    b.HasOne("KsSquare.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_orders_users_customer_id");
                });

            modelBuilder.Entity("KsSquare.Domain.Entities.EmailOtp", b =>
                {
                    b.HasOne("KsSquare.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_email_otps_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KsSquare.Domain.Entities.Product", b =>
                {
                    b.HasOne("KsSquare.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("KsSquare.Domain.Entities.ProductBraceletVariant", b =>
                {
                    b.HasOne("KsSquare.Domain.Entities.ProductOption", "BraceletSizeOption")
                        .WithMany()
                        .HasForeignKey("BraceletSizeOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_product_bracelet_variants_product_options_bracelet_size_opt");

                    b.HasOne("KsSquare.Domain.Entities.ProductOption", "BraceletStoneSizeOption")
                        .WithMany()
                        .HasForeignKey("BraceletStoneSizeOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_product_bracelet_variants_product_options_bracelet_stone_si");

                    b.HasOne("KsSquare.Domain.Entities.Product", "Product")
                        .WithMany("BraceletVariants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_bracelet_variants_products_product_id");

                    b.Navigation("BraceletSizeOption");

                    b.Navigation("BraceletStoneSizeOption");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("KsSquare.Domain.Entities.ProductChainVariant", b =>
                {
                    b.HasOne("KsSquare.Domain.Entities.ProductOption", "ChainDiamondSizeOption")
                        .WithMany()
                        .HasForeignKey("ChainDiamondSizeOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_product_chain_variants_product_options_chain_diamond_size_o");

                    b.HasOne("KsSquare.Domain.Entities.ProductOption", "ChainSizeOption")
                        .WithMany()
                        .HasForeignKey("ChainSizeOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_chain_variants_product_options_chain_size_option_id");

                    b.HasOne("KsSquare.Domain.Entities.ProductOption", "ChainWidthOption")
                        .WithMany()
                        .HasForeignKey("ChainWidthOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_product_chain_variants_product_options_chain_width_option_id");

                    b.HasOne("KsSquare.Domain.Entities.Product", "Product")
                        .WithMany("ChainVariants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_chain_variants_products_product_id");

                    b.Navigation("ChainDiamondSizeOption");

                    b.Navigation("ChainSizeOption");

                    b.Navigation("ChainWidthOption");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("KsSquare.Domain.Entities.ProductMedia", b =>
                {
                    b.HasOne("KsSquare.Domain.Entities.Product", "Product")
                        .WithMany("Media")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_media_products_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("KsSquare.Domain.Entities.ProductPendantVariant", b =>
                {
                    b.HasOne("KsSquare.Domain.Entities.ProductOption", "PendantSizeOption")
                        .WithMany()
                        .HasForeignKey("PendantSizeOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_pendant_variants_product_options_pendant_size_optio");

                    b.HasOne("KsSquare.Domain.Entities.Product", "Product")
                        .WithMany("PendantVariants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_pendant_variants_products_product_id");

                    b.Navigation("PendantSizeOption");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProductOptionAssignment", b =>
                {
                    b.HasOne("KsSquare.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_option_assignments_products_product_id");

                    b.HasOne("KsSquare.Domain.Entities.ProductOption", null)
                        .WithMany()
                        .HasForeignKey("ProductOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_option_assignments_product_options_product_option_id");
                });

            modelBuilder.Entity("ProductSubcategoryAssignment", b =>
                {
                    b.HasOne("KsSquare.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_subcategory_assignments_products_product_id");

                    b.HasOne("KsSquare.Domain.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_subcategory_assignments_categories_subcategory_id");
                });

            modelBuilder.Entity("KsSquare.Domain.Entities.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("KsSquare.Domain.Entities.CustomJewelryRequest", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("KsSquare.Domain.Entities.Product", b =>
                {
                    b.Navigation("BraceletVariants");

                    b.Navigation("ChainVariants");

                    b.Navigation("Media");

                    b.Navigation("PendantVariants");
                });
#pragma warning restore 612, 618
        }
    }
}
